In [2]:
import pandas as pd
import numpy as  np
import json

In [9]:
data=pd.read_json("C:\\Users\\a\\OneDrive\\Desktop\\AL ML PATNA\data\data\\trend_20240115.json")

In [10]:
data.head()

,post_id,title,category,score,num_comments,author,collected_at
0,47655408,Show HN: I built a tiny LLM to demystify how l...,technology,437,41,armanified,2026-04-06 14:45:00.907628
1,47658146,France pulls last gold held in US for $15B gain,technology,53,32,teleforce,2026-04-06 14:45:02.028235
2,47622591,Jobs Being Created by AI,technology,9,3,Jimmc414,2026-04-06 14:45:11.403969
3,47655367,Show HN: Gemma Gem – AI model embedded in a br...,technology,75,14,ikessler,2026-04-06 14:45:12.495743
4,47652007,"Show HN: Real-time AI (audio/video in, voice o...",technology,79,4,karimf,2026-04-06 14:45:16.003689

In [11]:
data.duplicated().sum()

np.int64(0)

In [12]:
data.isnull().sum()

post_id         0
title           0
category        0
score           0
num_comments    0
author          0
collected_at    0
dtype: int64

In [13]:
data.dtypes

post_id                  int64
title                   object
category                object
score                    int64
num_comments             int64
author                  object
collected_at    datetime64[ns]
dtype: object

In [14]:
data=data[data["score"]>=5]

In [15]:
data.shape

(78, 7)

In [16]:
data["title"]=data["title"].str.strip( )

In [ ]:
data

,post_id,title,category,score,num_comments,author,collected_at
0,47655408,Show HN: I built a tiny LLM to demystify how l...,technology,437,41,armanified,2026-04-06 14:45:00.907628
1,47658146,France pulls last gold held in US for $15B gain,technology,53,32,teleforce,2026-04-06 14:45:02.028235
2,47622591,Jobs Being Created by AI,technology,9,3,Jimmc414,2026-04-06 14:45:11.403969
3,47655367,Show HN: Gemma Gem – AI model embedded in a br...,technology,75,14,ikessler,2026-04-06 14:45:12.495743
4,47652007,"Show HN: Real-time AI (audio/video in, voice o...",technology,79,4,karimf,2026-04-06 14:45:16.003689
...,...,...,...,...,...,...,...
75,47638532,Show HN: Ownscribe – local meeting transcripti...,entertainment,15,0,paberr,2026-04-06 16:33:00.775128
76,47632692,Show HN: Mtproto.zig – High-performance Telegr...,entertainment,23,14,slp3r,2026-04-06 16:33:11.235368
77,47631030,Show HN: Ismcpdead.com – Live dashboard tracki...,entertainment,37,23,sagirodin,2026-04-06 16:33:14.184544
78,47612601,"Sweden goes back to basics, swapping screens f...",entertainment,900,432,novaRom,2026-04-06 16:33:24.861076
79,47643580,Show HN: Uncompressed – Self-hosted Netflix al...,entertainment,8,0,lackoftactics,2026-04-06 16:33:27.666235

In [17]:
data.to_csv("trends_clean.csv",index=False)